"""
Hardcoded fallback Game Bible for demo resilience.

If Mistral Large fails or returns invalid JSON, this is used so
the game can still run during the hackathon demo.
"""

FALLBACK_GAME_BIBLE: dict = {
    "world": {
        "title": "The Lost Kingdom of Aethermoor",
        "setting": "A crumbling kingdom on the edge of a dark forest, where magic fades and old alliances fracture.",
        "end_goal": "Reunite the three elder crystals to restore the kingdom's protective barrier.",
        "tone": "adventure",
    },
    "characters": [
        {
            "id": "char_elena",
            "name": "Elena the Wanderer",
            "archetype": "warrior",
            "role": "protagonist",
            "motivation": "Redeem her family's honour by saving the kingdom she was banished from.",
            "personality_traits": ["brave", "stubborn", "compassionate"],
            "relationship_to_player": "friendly",
            "convincing_triggers": ["mention her family", "show bravery"],
            "trust_threshold": 40,
            "dialogue_tree": {
                "greeting": "Well met, traveller. These roads aren't safe anymore.",
                "cooperative": "I'll fight alongside you. Let's end this.",
                "resistant": "I've been burned before. Prove yourself first.",
                "convinced": "You remind me why I started this journey. Lead the way.",
            },
            "portrait_prompt": "Fantasy portrait painting of a young woman warrior with short silver hair, leather armour with blue accents, determined expression, warm torchlight, detailed face, RPG character art style",
            "sprite_key": "warrior",
        },
        {
            "id": "char_grimshaw",
            "name": "Grimshaw the Merchant",
            "archetype": "merchant",
            "role": "npc",
            "motivation": "Profit from the chaos, but secretly wishes for peace.",
            "personality_traits": ["shrewd", "humorous", "cowardly"],
            "relationship_to_player": "neutral",
            "convincing_triggers": ["offer gold", "appeal to peace"],
            "trust_threshold": 55,
            "dialogue_tree": {
                "greeting": "Ah, a customer! Or perhaps a thief? Hard to tell these days.",
                "cooperative": "Fine, fine — I'll give you a discount. Don't tell anyone.",
                "resistant": "Nothing's free, friend. What's in it for me?",
                "convinced": "You're alright. Take this — you'll need it more than I will.",
            },
            "portrait_prompt": "Fantasy portrait painting of a stout middle-aged merchant man with a thick brown beard, colourful patchwork robes, sly grin, market stall background, warm lighting, RPG character art style",
            "sprite_key": "merchant",
        },
        {
            "id": "char_morvaine",
            "name": "Morvaine the Shadowed",
            "archetype": "villain",
            "role": "antagonist",
            "motivation": "Seize the elder crystals to reshape the kingdom under her rule.",
            "personality_traits": ["cunning", "charismatic", "ruthless"],
            "relationship_to_player": "hostile",
            "convincing_triggers": ["show vulnerability", "challenge her logic"],
            "trust_threshold": 80,
            "dialogue_tree": {
                "greeting": "You dare approach me? Interesting.",
                "cooperative": "Perhaps we aren't so different after all.",
                "resistant": "You're wasting my time — and yours.",
                "convinced": "Very well. I'll stay my hand… for now.",
            },
            "portrait_prompt": "Fantasy portrait painting of a tall imposing woman with flowing black hair, dark robes with crimson runes, piercing violet eyes, shadowy throne room background, dramatic lighting, RPG character art style",
            "sprite_key": "villain",
        },
        {
            "id": "char_aldric",
            "name": "Elder Aldric",
            "archetype": "elder",
            "role": "ally",
            "motivation": "Preserve the old knowledge before it's lost forever.",
            "personality_traits": ["wise", "patient", "melancholic"],
            "relationship_to_player": "friendly",
            "convincing_triggers": ["ask about history", "show respect"],
            "trust_threshold": 35,
            "dialogue_tree": {
                "greeting": "Ah, young one. The winds carry news of your arrival.",
                "cooperative": "The old texts speak of a way. Let me show you.",
                "resistant": "Patience. Not all knowledge is meant to be rushed.",
                "convinced": "You have the heart of the old heroes. Take this wisdom.",
            },
            "portrait_prompt": "Fantasy portrait painting of an elderly man with a long white beard, deep blue robes, kind weathered face, ancient library background, candlelight, RPG character art style",
            "sprite_key": "elder",
        },
    ],
    "tasks": [
        {
            "id": "task_01",
            "title": "Seek the Elder's Counsel",
            "description": "Find Elder Aldric in the town library and learn the location of the first crystal.",
            "type": "information_gather",
            "assigned_npc": "char_aldric",
            "unlocks": ["task_02"],
            "requires": [],
            "blocking": True,
            "completion_condition": "Gain Elder Aldric's trust and receive the map fragment.",
            "reward": "Map to the Forest Crystal",
        },
        {
            "id": "task_02",
            "title": "The Forest Crystal",
            "description": "Venture into the dark forest and retrieve the first elder crystal from the ancient shrine.",
            "type": "item_fetch",
            "assigned_npc": None,
            "unlocks": ["task_03"],
            "requires": ["task_01"],
            "blocking": True,
            "completion_condition": "Reach the forest shrine and collect the crystal.",
            "reward": "Forest Elder Crystal",
        },
        {
            "id": "task_03",
            "title": "Grimshaw's Bargain",
            "description": "The merchant Grimshaw has information about the dungeon crystal, but he wants something in return.",
            "type": "npc_persuasion",
            "assigned_npc": "char_grimshaw",
            "unlocks": ["task_04"],
            "requires": ["task_02"],
            "blocking": True,
            "completion_condition": "Convince Grimshaw to reveal the dungeon entrance.",
            "reward": "Dungeon Key",
        },
        {
            "id": "task_04",
            "title": "The Dungeon Crystal",
            "description": "Navigate the crumbling dungeon beneath the castle and claim the second crystal.",
            "type": "item_fetch",
            "assigned_npc": None,
            "unlocks": ["task_05"],
            "requires": ["task_03"],
            "blocking": True,
            "completion_condition": "Solve the dungeon puzzle and collect the crystal.",
            "reward": "Dungeon Elder Crystal",
        },
        {
            "id": "task_05",
            "title": "Confront the Shadowed",
            "description": "Face Morvaine in the castle throne room. Convince or defeat her to claim the final crystal.",
            "type": "moral_choice",
            "assigned_npc": "char_morvaine",
            "unlocks": [],
            "requires": ["task_04"],
            "blocking": True,
            "completion_condition": "Obtain the third crystal through persuasion or force.",
            "reward": "Castle Elder Crystal + Kingdom Restored",
        },
    ],
    "story_graph": {
        "opening_scene": "You arrive at the crumbling gates of Aethermoor as dusk falls. The once-proud kingdom is shrouded in unnatural fog. Somewhere within, three elder crystals hold the key to salvation — or destruction.",
        "acts": [
            {
                "act_number": 1,
                "title": "Gathering Allies",
                "description": "Meet the remaining inhabitants and learn the kingdom's plight.",
                "tasks_in_act": ["task_01"],
                "location": "town",
            },
            {
                "act_number": 2,
                "title": "Into the Wild",
                "description": "Brave the dark forest to claim the first crystal.",
                "tasks_in_act": ["task_02", "task_03"],
                "location": "forest",
            },
            {
                "act_number": 3,
                "title": "The Final Stand",
                "description": "Descend into the dungeon and confront Morvaine for the kingdom's fate.",
                "tasks_in_act": ["task_04", "task_05"],
                "location": "castle",
            },
        ],
        "ending_scene": "The three crystals blaze with light as you place them on the ancient pedestal. The fog lifts, the barrier shimmers into existence, and Aethermoor begins to heal. Your legend has just begun.",
    },
    "locations": [
        {
            "id": "loc_town",
            "name": "Aethermoor Town Square",
            "type": "town",
            "background_key": "town",
            "npcs_present": ["char_aldric", "char_grimshaw"],
            "connected_to": ["loc_forest", "loc_marketplace"],
        },
        {
            "id": "loc_marketplace",
            "name": "Grimshaw's Market",
            "type": "marketplace",
            "background_key": "marketplace",
            "npcs_present": ["char_grimshaw"],
            "connected_to": ["loc_town"],
        },
        {
            "id": "loc_forest",
            "name": "The Dark Forest",
            "type": "forest",
            "background_key": "forest",
            "npcs_present": ["char_elena"],
            "connected_to": ["loc_town", "loc_dungeon"],
        },
        {
            "id": "loc_dungeon",
            "name": "The Forgotten Depths",
            "type": "dungeon",
            "background_key": "dungeon",
            "npcs_present": [],
            "connected_to": ["loc_forest", "loc_castle"],
        },
        {
            "id": "loc_castle",
            "name": "Castle Aethermoor",
            "type": "castle",
            "background_key": "castle",
            "npcs_present": ["char_morvaine"],
            "connected_to": ["loc_dungeon", "loc_town"],
        },
    ],
}
