"""
Hardcoded fallback Game Bible for demo resilience.

If the 3-step Mistral pipeline fails or returns invalid JSON,
this is used so the game can still run during the hackathon demo.

Schema matches the fully dynamic version — no fixed archetypes or terrain types.
"""

FALLBACK_GAME_BIBLE: dict = {
    "world": {
        "title": "The Lost Kingdom of Aethermoor",
        "setting": "A crumbling medieval kingdom on the edge of a dark forest, where magic fades and old alliances fracture. The barrier that once protected the land is failing.",
        "end_goal": "Reunite the three elder crystals to restore the kingdom's protective barrier.",
        "tone": "epic fantasy adventure with melancholic undertones",
        "time_of_day": "dusk",
        "weather": "fog",
    },
    "characters": [
        {
            "id": "char_elena",
            "name": "Elena the Wanderer",
            "description": "A disgraced knight who was banished from the kingdom she once swore to protect. She now roams the forest edge, hunting remnants of the old magic.",
            "visual_description": "Young woman in her late 20s, short silver hair, battered leather armour with faded blue insignia, determined jaw, a long scar across her left cheek, carrying a notched sword",
            "role": "protagonist",
            "motivation": "Redeem her family's honour by saving the kingdom she was banished from — even if it kills her.",
            "personality_traits": ["brave", "stubborn", "compassionate"],
            "relationship_to_player": "friendly",
            "convincing_triggers": [
                "Player IS Elena — no convincing needed",
                "Player IS Elena — no convincing needed",
                "Player IS Elena — no convincing needed",
            ],
            "trust_threshold": 0,
            "movement_style": "walks with purpose, hand resting on sword hilt, occasionally surveys surroundings",
            "sprite_prompt": "pixel art RPG sprite, young woman late 20s, short silver hair, battered leather armour with blue insignia, notched sword, scar on cheek, determined expression, front-facing, full body, transparent background, 64x64, 16-bit style",
            "portrait_prompt": "pixel art RPG portrait, young woman late 20s, short silver hair, battered leather armour, scar across left cheek, intense determined eyes, close-up face and shoulders, detailed expression, 64x64, 16-bit style",
            "dialogue_tree": {
                "greeting": "I don't have time for pleasantries. Every day the barrier weakens is a day closer to the end.",
                "resistant": "I work alone. I've learned not to trust strangers since the banishment.",
                "cooperative": "You understand what it means to lose everything. Maybe we can work together.",
                "convinced": "Fine. But if you slow me down or betray me, I will leave you behind without hesitation.",
            },
        },
        {
            "id": "char_grimshaw",
            "name": "Grimshaw",
            "description": "A travelling merchant who profits from the kingdom's chaos but secretly wishes for peace. He knows every road, every rumour, and every shortcut — for a price.",
            "visual_description": "Stout man in his mid 50s, thick brown beard with grey streaks, colourful patchwork robes over practical travelling clothes, sly grin, carrying an absurdly large backpack",
            "role": "npc",
            "motivation": "Profit from the chaos, but deep down he misses the peaceful days when trade was honest and roads were safe.",
            "personality_traits": ["shrewd", "humorous", "secretly sentimental"],
            "relationship_to_player": "neutral",
            "convincing_triggers": [
                "Offer to restore the trade routes by fixing the barrier — appeal to his lost livelihood",
                "Mention the name of his dead wife Elara — remind him what peace meant to him",
                "Show him the merchant guild token from the old days — prove you respect what trade once was",
            ],
            "trust_threshold": 55,
            "movement_style": "waddles between market stalls, adjusts his backpack, whistles a merchant's tune",
            "sprite_prompt": "pixel art RPG sprite, stout man mid 50s, thick brown beard, colourful patchwork robes, large backpack, sly grin, front-facing, full body, transparent background, 64x64, 16-bit style",
            "portrait_prompt": "pixel art RPG portrait, stout man mid 50s, thick brown beard with grey streaks, patchwork robes, sly calculating grin, warm eyes, close-up face and shoulders, 64x64, 16-bit style",
            "dialogue_tree": {
                "greeting": "Ah, a customer! Or perhaps a thief? Hard to tell these days.",
                "resistant": "Nothing's free, friend. What's in it for me?",
                "cooperative": "You're not like the others. Most people just take — you actually ask.",
                "convinced": "You're alright. Take this — you'll need it more than I will. And Grimshaw never says that.",
            },
        },
        {
            "id": "char_morvaine",
            "name": "Morvaine the Shadowed",
            "description": "A former court wizard who seized one of the elder crystals after the kingdom fell. She believes ruling through power is the only way to prevent the chaos from spreading.",
            "visual_description": "Tall imposing woman in her 40s, flowing black hair with silver streaks, dark robes covered in faintly glowing crimson runes, piercing violet eyes, completely still posture",
            "role": "antagonist",
            "motivation": "Seize all three elder crystals to reshape the kingdom under her rule. She isn't purely evil — she genuinely believes democracy failed and only raw power can save what remains.",
            "personality_traits": ["cunning", "charismatic", "ideologically rigid"],
            "relationship_to_player": "hostile",
            "convincing_triggers": [
                "Prove that the barrier's collapse will destroy her too — show her the decay map from Elder Aldric's library",
                "Remind her of her original oath as court wizard — use her real name, Sera Morvaine, which no one has called her in years",
                "Admit that Elena's family were wrong to exile her — acknowledge the injustice she suffered",
            ],
            "trust_threshold": 82,
            "movement_style": "stands perfectly still on her throne, only her eyes move, robes shift as if blown by a wind no one else feels",
            "sprite_prompt": "pixel art RPG sprite, tall woman 40s, flowing black hair, dark robes with glowing crimson runes, violet eyes, imposing stance, front-facing, full body, transparent background, 64x64, 16-bit style",
            "portrait_prompt": "pixel art RPG portrait, tall woman 40s, flowing black hair with silver streaks, dark robes, piercing violet eyes, cold commanding expression, close-up face and shoulders, 64x64, 16-bit style",
            "dialogue_tree": {
                "greeting": "You dare approach me? Interesting. Most who enter this room don't leave it.",
                "resistant": "Your idealism is quaint. The old kingdom fell because it was weak. I will not be.",
                "cooperative": "You've done your research. I'll give you that. Perhaps we aren't so different.",
                "convinced": "Very well. Perhaps I chose the wrong enemies. The barrier matters more than this throne.",
            },
        },
        {
            "id": "char_aldric",
            "name": "Elder Aldric",
            "description": "The last keeper of the old knowledge. A retired scholar who has spent decades cataloguing the kingdom's history. He knows where the crystals are — but his trust must be earned.",
            "visual_description": "Elderly man in his 80s, long white beard, deep blue robes faded at the cuffs, kind but tired eyes, ink-stained fingers, always holding a scroll",
            "role": "ally",
            "motivation": "Preserve the old knowledge before it's lost forever. He's watched three generations fail to save the kingdom and is afraid to hope again.",
            "personality_traits": ["wise", "patient", "afraid to hope"],
            "relationship_to_player": "friendly",
            "convincing_triggers": [
                "Ask about the history of the elder crystals — show genuine interest in his life's work",
                "Bring him the fragment of the old barrier stone from the forest shrine — prove you've already started the quest",
                "Tell him you know the journey might fail — he respects honesty over blind optimism",
            ],
            "trust_threshold": 38,
            "movement_style": "shuffles slowly between bookshelves, occasionally stops to read a passage, mutters to himself",
            "sprite_prompt": "pixel art RPG sprite, elderly man 80s, long white beard, deep blue robes, ink-stained fingers, holding scroll, gentle posture, front-facing, full body, transparent background, 64x64, 16-bit style",
            "portrait_prompt": "pixel art RPG portrait, elderly man 80s, long white beard, deep blue robes, kind tired eyes, ink-stained fingers, warm candlelight, close-up face and shoulders, 64x64, 16-bit style",
            "dialogue_tree": {
                "greeting": "Ah, young one. The winds carry news of your arrival. I've been waiting — and dreading.",
                "resistant": "Patience. Not all knowledge is meant to be rushed. I've seen eager fools before.",
                "cooperative": "You have a genuine spirit. The old texts speak of a way. Let me show you.",
                "convinced": "You have the heart of the old heroes. Take this wisdom — it's all I have left to give.",
            },
        },
    ],
    "tasks": [
        {
            "id": "task_01",
            "title": "Seek the Elder's Counsel",
            "description": "Find Elder Aldric in the town library and learn the location of the first crystal. He's the only person alive who has read the original barrier texts.",
            "type": "knowledge acquisition",
            "assigned_npc": "char_aldric",
            "unlocks": ["task_02"],
            "requires": [],
            "blocking": True,
            "completion_condition": "char_aldric trust_level >= 38 AND player receives item map_fragment",
            "reward": "Map fragment showing the forest crystal's location — required for task_02",
        },
        {
            "id": "task_02",
            "title": "The Forest Crystal",
            "description": "Venture into the dark forest and retrieve the first elder crystal from the ancient shrine. The path is dangerous and the forest itself resists intruders.",
            "type": "exploration and retrieval",
            "assigned_npc": None,
            "unlocks": ["task_03"],
            "requires": ["task_01"],
            "blocking": True,
            "completion_condition": "Player reaches forest shrine AND retrieves item forest_crystal",
            "reward": "Forest Elder Crystal — first of three needed to restore the barrier",
        },
        {
            "id": "task_03",
            "title": "Grimshaw's Bargain",
            "description": "Grimshaw knows the hidden entrance to the dungeons beneath the castle where the second crystal rests. But he won't share it for free — he needs to believe it's worth his risk.",
            "type": "persuasion and negotiation",
            "assigned_npc": "char_grimshaw",
            "unlocks": ["task_04"],
            "requires": ["task_02"],
            "blocking": True,
            "completion_condition": "char_grimshaw trust_level >= 55",
            "reward": "Dungeon entrance location and key — required for task_04",
        },
        {
            "id": "task_04",
            "title": "The Dungeon Crystal",
            "description": "Navigate the crumbling dungeon beneath the castle and claim the second crystal. The dungeon is collapsing — speed matters more than caution.",
            "type": "timed dungeon navigation",
            "assigned_npc": None,
            "unlocks": ["task_05"],
            "requires": ["task_03"],
            "blocking": True,
            "completion_condition": "Player navigates dungeon AND retrieves item dungeon_crystal within time limit",
            "reward": "Dungeon Elder Crystal — second of three",
        },
        {
            "id": "task_05",
            "title": "Confront the Shadowed",
            "description": "Morvaine holds the final crystal in the castle throne room. She must be convinced to surrender it — or it must be taken by force. Either path changes the ending.",
            "type": "moral confrontation",
            "assigned_npc": "char_morvaine",
            "unlocks": [],
            "requires": ["task_04"],
            "blocking": True,
            "completion_condition": "char_morvaine trust_level >= 82 OR player defeats morvaine in final challenge",
            "reward": "Castle Elder Crystal — barrier restored, ending scene triggered",
        },
    ],
    "story_graph": {
        "opening_scene": "Elena stands at the crumbling gates of Aethermoor as dusk falls. Fog rolls through the broken battlements. On the wind: the faint hum of a dying barrier. She has three days before it fails completely.",
        "acts": [
            {
                "act_number": 1,
                "title": "Gathering Allies",
                "description": "Meet the remaining inhabitants and learn the kingdom's plight from Elder Aldric.",
                "tasks_in_act": ["task_01"],
                "location_id": "loc_town",
            },
            {
                "act_number": 2,
                "title": "Into the Wild",
                "description": "Brave the dark forest to claim the first crystal, then earn Grimshaw's trust for the dungeon entrance.",
                "tasks_in_act": ["task_02", "task_03"],
                "location_id": "loc_forest",
            },
            {
                "act_number": 3,
                "title": "The Final Stand",
                "description": "Descend into the dungeon and confront Morvaine for the kingdom's fate.",
                "tasks_in_act": ["task_04", "task_05"],
                "location_id": "loc_castle",
            },
        ],
        "ending_scene": "The three crystals blaze with light as Elena places them on the ancient pedestal. The fog lifts. The barrier shimmers back into existence. Aethermoor begins to heal — slowly, imperfectly, but real. Elena watches the sunrise for the first time in years.",
    },
    "locations": [
        {
            "id": "loc_town",
            "name": "Aethermoor Town Square",
            "description": "A once-grand town square now cracked and overgrown. Market stalls stand empty. The library is the only building with light.",
            "terrain_type": "cracked cobblestone with overgrown weeds",
            "background_prompt": "pixel art RPG background, crumbling medieval town square at dusk, cracked cobblestone, overgrown weeds, empty market stalls, single lit library window, fog rolling in, faded banners, no characters, no text, 16-bit style, 1280x720",
            "tile_map_prompt": "20x15 tile map, town square layout, cobblestone walkable center area, broken stall obstacles at edges, library building at top center, fountain structure in middle, overgrown areas as soft obstacles, spawn points: player_start at south gate, npc_spawn_1 at library for char_aldric, npc_spawn_2 at market stalls for char_grimshaw",
            "movement_profile": {
                "speed": 110,
                "friction": 0.8,
                "camera_shake": False,
                "ambient_sound": "wind through empty streets, distant creaking wood, faint barrier hum",
                "step_sound": "cobblestone",
            },
            "npcs_present": ["char_aldric", "char_grimshaw"],
            "npc_spawn_slots": {
                "char_aldric": "npc_spawn_1",
                "char_grimshaw": "npc_spawn_2",
            },
            "player_spawn": "player_start",
            "connected_to": ["loc_forest", "loc_marketplace"],
        },
        {
            "id": "loc_marketplace",
            "name": "Grimshaw's Corner",
            "description": "A sheltered corner of the market where Grimshaw has set up his travelling shop. Lanterns hang from ropes. Everything is for sale — at his price.",
            "terrain_type": "packed dirt with scattered straw",
            "background_prompt": "pixel art RPG background, medieval market corner at dusk, hanging lanterns, travelling merchant's stall with colorful goods, packed dirt floor, straw scattered, warm lantern light, fog at edges, no characters, no text, 16-bit style, 1280x720",
            "tile_map_prompt": "20x15 tile map, small market area, dirt walkable floor, merchant stall as large obstacle at center-right, crate and barrel obstacles around edges, lantern posts, spawn points: player_start at left entry, npc_spawn_1 at merchant stall for char_grimshaw",
            "movement_profile": {
                "speed": 100,
                "friction": 0.6,
                "camera_shake": False,
                "ambient_sound": "lantern creaking, distant town sounds, occasional merchant humming",
                "step_sound": "dirt",
            },
            "npcs_present": ["char_grimshaw"],
            "npc_spawn_slots": {
                "char_grimshaw": "npc_spawn_1",
            },
            "player_spawn": "player_start",
            "connected_to": ["loc_town"],
        },
        {
            "id": "loc_forest",
            "name": "The Dark Forest",
            "description": "Ancient trees block the sky. The path is barely visible. The forest feels alive and hostile — branches move without wind.",
            "terrain_type": "dense forest floor with roots and mud",
            "background_prompt": "pixel art RPG background, dark ancient forest at dusk, massive gnarled trees, barely visible path, roots crossing ground, mist between trees, faint eerie glow from distant shrine, no characters, no text, 16-bit style, 1280x720",
            "tile_map_prompt": "20x15 tile map, dense forest, narrow winding walkable paths between tree obstacles, root obstacles across paths, clearing at right side for shrine, mushrooms and rocks as small obstacles, spawn points: player_start at left edge path entry, npc_spawn_1 at forest clearing for char_elena",
            "movement_profile": {
                "speed": 65,
                "friction": 0.5,
                "camera_shake": False,
                "ambient_sound": "wind through canopy, distant animal calls, branches creaking, faint magical hum",
                "step_sound": "forest_floor",
            },
            "npcs_present": ["char_elena"],
            "npc_spawn_slots": {
                "char_elena": "npc_spawn_1",
            },
            "player_spawn": "player_start",
            "connected_to": ["loc_town", "loc_dungeon"],
        },
        {
            "id": "loc_dungeon",
            "name": "The Forgotten Depths",
            "description": "Crumbling stone corridors beneath the castle. Water drips from the ceiling. The walls groan. This place is collapsing — slowly, but unstoppably.",
            "terrain_type": "wet crumbling stone with standing water",
            "background_prompt": "pixel art RPG background, medieval dungeon corridor, crumbling stone walls, standing water on floor, dripping ceiling, dim torch sconces, rubble piles, oppressive darkness beyond torchlight, no characters, no text, 16-bit style, 1280x720",
            "tile_map_prompt": "20x15 tile map, dungeon corridor layout, stone walkable paths, rubble obstacles blocking some corridors, standing water tiles in low areas, torch sconces on walls, collapsed section at top as impassable obstacle, crystal chamber at far end, spawn points: player_start at entry stairs bottom-left",
            "movement_profile": {
                "speed": 55,
                "friction": 0.4,
                "camera_shake": True,
                "ambient_sound": "dripping water, distant stone grinding, echoing footsteps, occasional collapse rumble",
                "step_sound": "wet_stone",
            },
            "npcs_present": [],
            "npc_spawn_slots": {},
            "player_spawn": "player_start",
            "connected_to": ["loc_forest", "loc_castle"],
        },
        {
            "id": "loc_castle",
            "name": "Castle Aethermoor — Throne Room",
            "description": "The grand throne room, half in ruins. Morvaine sits on the cracked throne, the final crystal pulsing in her hand. Torn banners hang from the ceiling.",
            "terrain_type": "cracked marble floor with debris",
            "background_prompt": "pixel art RPG background, ruined medieval castle throne room, cracked marble floor, half-collapsed columns, single intact throne at far end, torn royal banners, pulsing crystal glow, dramatic shadows, no characters, no text, 16-bit style, 1280x720",
            "tile_map_prompt": "20x15 tile map, throne room, wide marble walkable center aisle, collapsed column obstacles on sides, throne platform at top center, debris piles as small obstacles, crystal pedestal near throne, spawn points: player_start at grand door bottom center, npc_spawn_1 at throne for char_morvaine",
            "movement_profile": {
                "speed": 90,
                "friction": 0.7,
                "camera_shake": False,
                "ambient_sound": "wind through broken windows, crystal humming, distant barrier crackling, stone settling",
                "step_sound": "marble",
            },
            "npcs_present": ["char_morvaine"],
            "npc_spawn_slots": {
                "char_morvaine": "npc_spawn_1",
            },
            "player_spawn": "player_start",
            "connected_to": ["loc_dungeon", "loc_town"],
        },
    ],
}
